import type { InventoryAsset } from "./types";

export const baselineInventory: InventoryAsset[] = [
  {
    id: "SITE-ALPHA",
    name: "Site Alpha",
    kind: "site",
    site: "Site Alpha",
    status: "active",
    source: "inventory",
    detail: "14 circuits",
    lastObserved: "Today, 16:18",
  },
  {
    id: "SW-1",
    name: "Aggregation Switch 1",
    kind: "switch",
    site: "Site Alpha",
    status: "active",
    source: "field_observation",
    detail: "Shared dependency detected",
    lastObserved: "Today, 16:18",
  },
  {
    id: "SW-2",
    name: "Aggregation Switch 2",
    kind: "switch",
    site: "Site Alpha",
    status: "offline",
    source: "field_observation",
    detail: "Uplink removed",
    lastObserved: "Today, 16:18",
  },
  {
    id: "RADIO-A",
    name: "Primary Radio A",
    kind: "radio",
    site: "Site Alpha",
    status: "active",
    source: "inventory",
    detail: "Primary path",
    lastObserved: "Today, 16:18",
  },
  {
    id: "RADIO-B",
    name: "Backup Radio B",
    kind: "radio",
    site: "Site Alpha",
    status: "active",
    source: "field_observation",
    detail: "Observed on SW-1/8",
    lastObserved: "Today, 16:18",
  },
  {
    id: "TOWER-KILO",
    name: "Tower Kilo",
    kind: "site",
    site: "Tower Kilo",
    status: "active",
    source: "inventory",
    detail: "Field install in progress",
    lastObserved: "Today, 16:10",
  },
  {
    id: "RADIO-C",
    name: "Radio C",
    kind: "radio",
    site: "Tower Kilo",
    status: "proposed",
    source: "field_observation",
    detail: "Rack 2 · U18 · LC-8841",
    lastObserved: "Today, 16:10",
  },
  {
    id: "DISH-3",
    name: "Dish 3",
    kind: "antenna",
    site: "Tower Kilo",
    status: "active",
    source: "field_observation",
    detail: "18.7 GHz · Vertical",
    lastObserved: "Today, 16:10",
  },
  {
    id: "RADIO-D",
    name: "Site Bravo Radio D",
    kind: "radio",
    site: "Site Bravo",
    status: "active",
    source: "inventory",
    detail: "Remote endpoint",
    lastObserved: "Today, 16:10",
  },
  {
    id: "CORE",
    name: "Regional Core",
    kind: "core",
    site: "Regional POP",
    status: "active",
    source: "inventory",
    detail: "Transport core",
    lastObserved: "Today, 16:18",
  },
];

